"""Initial database schema

Revision ID: 54d9aaacdc6b
Revises: 
Create Date: 2025-05-04 12:02:46.727494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d9aaacdc6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.Enum('semantic', 'episodic', 'procedural', 'uncategorized', name='memory_type_enum'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_is_archived'), 'notes', ['is_archived'], unique=False)
    op.create_index(op.f('ix_notes_memory_type'), 'notes', ['memory_type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_note_id', sa.Uuid(), nullable=False),
    sa.Column('target_note_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_note_id <> target_note_id', name=op.f('ck_links_ck_links_no_self_referencing')),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], name=op.f('fk_links_source_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.id'], name=op.f('fk_links_target_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links')),
    sa.UniqueConstraint('source_note_id', 'target_note_id', name='uq_links_source_target')
    )
    op.create_index(op.f('ix_links_source_note_id'), 'links', ['source_note_id'], unique=False)
    op.create_index(op.f('ix_links_target_note_id'), 'links', ['target_note_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_tags_note_id_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_note_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id', name=op.f('pk_note_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_links_target_note_id'), table_name='links')
    op.drop_index(op.f('ix_links_source_note_id'), table_name='links')
    op.drop_table('links')
    op.drop_table('tags')
    op.drop_index(op.f('ix_notes_memory_type'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_archived'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
